# Generated by Django 5.2.14 on 2026-08-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0033_add_gif_product_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPage',
            fields=[
                ('productitempage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.productitempage')),
                ('doc', models.JSONField(blank=True, default=dict)),
                ('html', models.TextField(blank=True, default='')),
                ('is_template', models.BooleanField(default=False, verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
            },
            bases=('products.productitempage',),
        ),
    ]
