# Generated by Django 5.2.16 on 2026-10-04 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_studio', '0001_initial'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastMapSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.JSONField(blank=True, default=list)),
                ('days_ahead', models.PositiveSmallIntegerField(default=1, help_text="Draw today's maps and those of the following days: 0 for today only, 6 at most (a forecast pull covers a week).", validators=[django.core.validators.MaxValueValidator(6)], verbose_name='Days ahead')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Forecast map',
            },
        ),
    ]
