# Generated by Django 5.2.16 on 2026-10-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_studio', '0002_forecastmapsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpage',
            name='source_template',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='bulletin_studio.bulletinpage'),
        ),
    ]
