# Generated by Django 5.2.16 on 2026-10-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_studio', '0003_bulletinpage_source_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletinpage',
            name='daily_draft_at',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='bulletinpage',
            name='last_daily_draft',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
